# Generated by Django 3.0.3 on 2020-03-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('github_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('avatar', models.CharField(max_length=500)),
                ('issues', models.CharField(max_length=10)),
                ('commits', models.CharField(max_length=10)),
                ('tests', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('datetime_local', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('average_price', models.CharField(max_length=10)),
                ('event_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRecord',
            fields=[
                ('team_id_and_season', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('wins', models.CharField(max_length=5)),
                ('losses', models.CharField(max_length=5)),
                ('division_rank', models.CharField(max_length=10)),
                ('league_rank', models.CharField(max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('picture', models.CharField(max_length=300)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('player_id_and_season', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('games_played', models.CharField(max_length=10)),
                ('games_started', models.CharField(max_length=10)),
                ('wins', models.CharField(max_length=10)),
                ('losses', models.CharField(max_length=10)),
                ('era', models.CharField(max_length=10)),
                ('games_finished', models.CharField(max_length=10)),
                ('complete_games', models.CharField(max_length=10)),
                ('shutouts', models.CharField(max_length=10)),
                ('saves', models.CharField(max_length=10)),
                ('innings_pitched', models.CharField(max_length=10)),
                ('hits', models.CharField(max_length=10)),
                ('runs', models.CharField(max_length=10)),
                ('earned_runs', models.CharField(max_length=10)),
                ('home_runs', models.CharField(max_length=10)),
                ('walks', models.CharField(max_length=10)),
                ('strikeouts', models.CharField(max_length=10)),
                ('whip', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='HitterStats',
            fields=[
                ('player_id_and_season', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=10)),
                ('games', models.CharField(max_length=10)),
                ('plate_appearances', models.CharField(max_length=10)),
                ('at_bats', models.CharField(max_length=10)),
                ('runs', models.CharField(max_length=10)),
                ('hits', models.CharField(max_length=10)),
                ('doubles', models.CharField(max_length=10)),
                ('triples', models.CharField(max_length=10)),
                ('home_runs', models.CharField(max_length=10)),
                ('runs_batted_in', models.CharField(max_length=10)),
                ('stolen_bases', models.CharField(max_length=10)),
                ('caught_stealing', models.CharField(max_length=10)),
                ('strikeouts', models.CharField(max_length=10)),
                ('batting_average', models.CharField(max_length=10)),
                ('obp', models.CharField(max_length=10)),
                ('slg', models.CharField(max_length=10)),
                ('ops', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('current_inning', models.CharField(max_length=30)),
                ('game_datetime', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='apiapp.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('boxscore_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('home_runs', models.IntegerField()),
                ('home_hits', models.IntegerField()),
                ('home_lob', models.IntegerField()),
                ('away_runs', models.IntegerField()),
                ('away_hits', models.IntegerField()),
                ('away_lob', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Game')),
            ],
        ),
    ]
