# Generated by Django 3.0.3 on 2020-04-15 02:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20200415_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxscore',
            name='away_hits',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='away_lob',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='away_runs',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='home_hits',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='home_lob',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='home_runs',
        ),
        migrations.AddField(
            model_name='boxscore',
            name='away_hitting_totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxscore',
            name='away_pitching_totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxscore',
            name='home_hitting_totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxscore',
            name='home_pitching_totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
