# Generated by Django 3.0.3 on 2020-03-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20200229_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='users',
            new_name='user_ids',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
