# Generated by Django 3.0.3 on 2020-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20200415_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxscore',
            name='home_hitting_totals',
        ),
        migrations.AddField(
            model_name='team',
            name='video_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_channel_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
