# Generated by Django 3.0.3 on 2020-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
