# Generated by Django 3.0.3 on 2020-03-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20200301_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=2)),
                ('position', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
    ]
