# Generated by Django 3.0.3 on 2020-04-17 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_auto_20200417_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxscore',
            name='home_hitting_totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
