# Generated by Django 3.0.3 on 2020-03-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
