# Generated by Django 3.0.3 on 2020-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
    ]
