# Generated by Django 3.0.3 on 2020-03-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20200304_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
