# Generated by Django 3.0.3 on 2020-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_boxscore_home_hitting_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_prediction',
            field=models.IntegerField(default=0),
        ),
    ]
