# Generated by Django 3.0.3 on 2020-03-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20200304_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_name',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50),
        ),
    ]
