# Generated by Django 3.0.3 on 2020-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_auto_20200306_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.CharField(max_length=300),
        ),
    ]
