# Generated by Django 3.0.3 on 2020-04-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_auto_20200422_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='away_team_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='home_team_name',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
