# Generated by Django 3.0.3 on 2020-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_auto_20200306_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_inning',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
