# Generated by Django 3.0.3 on 2020-03-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_auto_20200307_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='currentInning',
            new_name='current_inning',
        ),
    ]
