# Generated by Django 3.0.3 on 2020-03-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_auto_20200307_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('avatar', models.CharField(max_length=500)),
                ('issues', models.CharField(max_length=10)),
                ('commits', models.CharField(max_length=10)),
                ('tests', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='user_ids',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
