# Generated by Django 3.0.3 on 2020-03-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_auto_20200320_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
