# Generated by Django 3.0.3 on 2020-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_auto_20200324_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
