# Generated by Django 3.0.3 on 2020-03-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_teamrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrecord',
            old_name='team_id',
            new_name='team',
        ),
    ]
