# Generated by Django 3.0.3 on 2020-03-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_auto_20200326_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('player_id_and_season', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('games_played', models.CharField(max_length=5)),
                ('games_started', models.CharField(max_length=5)),
                ('wins', models.CharField(max_length=5)),
                ('losses', models.CharField(max_length=5)),
                ('era', models.CharField(max_length=5)),
                ('games_finished', models.CharField(max_length=5)),
                ('complete_games', models.CharField(max_length=5)),
                ('shutouts', models.CharField(max_length=5)),
                ('saves', models.CharField(max_length=5)),
                ('innings_pitched', models.CharField(max_length=5)),
                ('hits', models.CharField(max_length=5)),
                ('runs', models.CharField(max_length=5)),
                ('earned_runs', models.CharField(max_length=5)),
                ('home_runs', models.CharField(max_length=5)),
                ('walks', models.CharField(max_length=5)),
                ('strikeouts', models.CharField(max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
        migrations.CreateModel(
            name='HitterStats',
            fields=[
                ('player_id_and_season', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('games', models.CharField(max_length=5)),
                ('plate_appearances', models.CharField(max_length=5)),
                ('at_bats', models.CharField(max_length=5)),
                ('runs', models.CharField(max_length=5)),
                ('hits', models.CharField(max_length=5)),
                ('doubles', models.CharField(max_length=5)),
                ('triples', models.CharField(max_length=5)),
                ('home_runs', models.CharField(max_length=5)),
                ('runs_batted_in', models.CharField(max_length=5)),
                ('stolen_bases', models.CharField(max_length=5)),
                ('caught_stealing', models.CharField(max_length=5)),
                ('strikeouts', models.CharField(max_length=5)),
                ('batting_average', models.CharField(max_length=5)),
                ('obp', models.CharField(max_length=5)),
                ('slg', models.CharField(max_length=5)),
                ('ops', models.CharField(max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Team')),
            ],
        ),
    ]
