# Generated by Django 3.0.3 on 2020-03-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_hitterstats_pitcherstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitterstats',
            name='season',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitcherstats',
            name='season',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
