# Generated by Django 3.0.3 on 2020-03-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_auto_20200327_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcherstats',
            name='whip',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
