# Generated by Django 3.0.3 on 2020-03-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_auto_20200327_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_date',
            new_name='game_datetime',
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='apiapp.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='apiapp.Team'),
        ),
    ]
