# Generated by Django 3.0.3 on 2020-03-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_auto_20200328_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitterstats',
            name='at_bats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='caught_stealing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='doubles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='games',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='hits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='home_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='obp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='plate_appearances',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='runs_batted_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='slg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='stolen_bases',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='strikeouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hitterstats',
            name='triples',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='complete_games',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='earned_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='era',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='games_finished',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='games_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='games_started',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='hits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='home_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='innings_pitched',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='losses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='saves',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='shutouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='strikeouts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='walks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='whip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='wins',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('boxscore_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('home_run_total', models.IntegerField()),
                ('away_run_total', models.IntegerField()),
                ('home_error_total', models.IntegerField()),
                ('away_error_total', models.IntegerField()),
                ('home_hit_total', models.IntegerField()),
                ('away_hit_total', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Game')),
                ('top_away_hitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_away_hitter', to='apiapp.Player')),
                ('top_home_hitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_home_hitter', to='apiapp.Player')),
            ],
        ),
    ]
