# Generated by Django 3.0.3 on 2020-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_auto_20200328_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('datetime_local', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('average_price', models.CharField(max_length=10)),
            ],
        ),
    ]
