# Generated by Django 3.0.3 on 2020-03-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_auto_20200330_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxscore',
            name='top_away_hitter',
        ),
        migrations.RemoveField(
            model_name='boxscore',
            name='top_home_hitter',
        ),
    ]
