# Generated by Django 3.0.3 on 2020-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_url',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
