# Generated by Django 3.0.3 on 2020-04-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0022_auto_20200331_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('boxscore_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('home_runs', models.IntegerField()),
                ('home_hits', models.IntegerField()),
                ('home_lob', models.IntegerField()),
                ('away_runs', models.IntegerField()),
                ('away_hits', models.IntegerField()),
                ('away_lob', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.Game')),
            ],
        ),
    ]
