# Generated by Django 3.0.3 on 2020-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0023_boxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
